name: Build ESPHome Configs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    name: Compile ESPHome configs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - interactive-map.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create secrets.yaml
        run: |
          cat <<'EOF' > secrets.yaml
          INTERACTIVE_MAP_WIFI_SSID: "hackme"
          INTERACTIVE_MAP_WIFI_PASSWORD: "password1234"
          INTERACTIVE_MAP_IDP_CLIENT_ID: "client-id"
          INTERACTIVE_MAP_IDP_CLIENT_SECRET: "client-secret"
          INTERACTIVE_MAP_IDP_TOKEN_URL: "https://auth.example.com/application/o/token/"
          INTERACTIVE_MAP_FEEDER_API_URL: "http://api.example.com/iot/interactive-map-feeder/v1/data-sources/radar/cities/iot"
          EOF
      - name: Build ${{ matrix.config }}
        uses: esphome/build-action@v6
        with:
          yaml-file: ${{ matrix.config }}
